name: netflix
version: 1.4.3+8
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_svg: #  flutter_svg: ^1.1.1+1
  reactive_forms: ^16.1.0
  permission_handler:
  bot_toast: ^4.0.3
  chopper: ^7.0.6
  logger: ^2.0.2+1
  get: ^4.6.6
  cached_network_image: #cached_network_image: ^3.2.1
  shimmer: ^3.0.0
  intl_phone_field:
    git: https://github.com/l00ai/intl_phone_field.git
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.0
  custom_searchable_dropdown: ^2.1.1
  sms_autofill: ^2.2.0
  dropdown_button2: #  dropdown_button2: ^1.6.3
  flutter_widget_from_html_core: any
  fwfh_webview: ^0.9.0+2
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.1.3
  location: ^5.0.3
  zoom_tap_animation: ^1.1.0

  intl: ^0.18.1
  image_picker: ^1.0.4
  flutter_html: any
  youtube_player_flutter:  #  youtube_player_flutter: ^8.1.0

#  flutter_facebook_auth:
  firebase_core: ^2.17.0
  firebase_messaging:
  awesome_notifications:
#  google_sign_in:
  shared_preferences: ^2.0.15


  flutter:
    sdk: flutter
  firebase_auth: ^4.6.3
  flutter_datetime_picker_plus: ^2.0.1
  change_app_package_name: ^1.1.0
  http: ^1.1.0
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  logging: ^1.2.0
  flutter_test:
    sdk: flutter
  video_player: ^2.7.2
  cloud_firestore: ^4.11.0
  video_compress: ^3.1.2
  file_selector: ^1.0.1
  video_thumbnail: ^0.5.3
  appinio_video_player: ^1.2.2
  native_video_view: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.3
  lints: ^2.1.1
  build_runner: ^2.1.4
  chopper_generator: ^7.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/netIcon.png
    - assets/images/netProf.png
    - assets/images/videoplayback.webm